language: go

go:
  - 1.6
  - tip

install:
  - go get github.com/RainInFall/assert
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - go generate

script: 
  - go test -v -covermode=count -coverprofile=array.out ./array
after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=array.out -service=travis-ci -repotoken $COVERALLS_TOKEN
